---
controller_manager:
  ros__parameters:
    cpu_affinity: 2
    update_rate: 1000

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    
    ackermann_steering_controller:    
      type: "ackermann_steering_controller/AckermannSteeringController"


ackermann_steering_controller:
  ros__parameters:
    position_feedback: false
    wheelbase: 0.6
    front_wheels_radius: 0.25
    rear_wheels_radius: 0.25
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ["left_rear_wheel_joint", "right_rear_wheel_joint"]
    front_wheels_names: ["left_front_wheel_joint", "right_front_wheel_joint"]
    front_wheel_track: 0.2
    rear_wheel_track: 0.2
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    use_stamped_vel: true
    open_loop: false
