---
controller_manager:
  ros__parameters:
    use_sim_time: false  # Set to true if using Gazebo/simulation
    cpu_affinity: 2
    update_rate: 100

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    
    gps_sensor_broadcaster:
      type: "gps_sensor_broadcaster/GPSSensorBroadcaster"

    ackermann_steering_controller:    
      type: "ackermann_steering_controller/AckermannSteeringController"
    
    robot_steering_controller:    
      type: "robot_steering_controller/RobotSteeringController"
        

ackermann_steering_controller:
  ros__parameters:
    use_sim_time: false  # Set to true if using Gazebo/simulation
    position_feedback: false
    wheelbase: 1.0
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1
    front_steering: true
    reference_timeout: 5.0
    rear_wheels_names: ["left_rear_wheel_joint", "right_rear_wheel_joint"]
    front_wheels_names: ["left_front_wheel_joint", "right_front_wheel_joint"]  # rolling joints
    front_wheel_track: 0.6
    rear_wheel_track: 0.6
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    use_stamped_vel: true
    open_loop: false
    cmd_topic: "/ackermann_cmd"  # controller will subscribe to this

robot_steering_controller:
  ros__parameters:
    use_sim_time: false  # Set to true if using Gazebo/simulation
    position_feedback: false
    wheelbase: 1.0
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ["left_rear_wheel_joint", "right_rear_wheel_joint"]
    front_wheels_names: ["left_front_wheel_joint", "right_front_wheel_joint"]  # rolling joints
    front_wheel_track: 0.6
    rear_wheel_track: 0.6
    gps_sensor_name: ["gps_sensor"]
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    use_stamped_vel: true
    open_loop: false
    cmd_topic: "/robot_cmd"  # controller will subscribe to this


gps_sensor_broadcaster:
  ros__parameters:
    use_sim_time: false  # Set to true if using Gazebo/simulation
    use_local_topics: true
    frame_id: gps_link
    sensors: ["gps_sensor"]
    interfaces: ["latitude", "longitude", "altitude"]