#ifndef GPS_SENSOR_BROADCASTER__GPS_SENSOR_BROADCASTER_HPP_
#define GPS_SENSOR_BROADCASTER__GPS_SENSOR_BROADCASTER_HPP_

#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "sensor_msgs/msg/nav_sat_fix.hpp"
#include "controller_interface/controller_interface.hpp"
#include "gps_sensor_broadcaster/visibility_control.h"
#include "rclcpp_lifecycle/lifecycle_publisher.hpp"
#include "rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "gps_sensor_broadcaster/param_listener.hpp"

// auto-generated by generate_parameter_library
#include "gps_sensor_broadcaster/gps_sensor_broadcaster.hpp"

namespace gps_sensor_broadcaster
{
  /**
   * \brief Joint State Broadcaster for all or some state in a ros2_control system.
   *
   * JointStateBroadcaster publishes state interfaces from ros2_control as ROS messages.
   * There is a possibility to publish all available states (typical use), or only specific ones.
   * The latter is, for example, used when hardware provides multiple measurement sources for some
   * of its states, e.g., position.
   * It is possible to define a mapping of measurements
   * from different sources stored in custom interfaces to standard dynamic names in JointState
   * message.
   * If "joints" or "interfaces" parameter is empty, all available states are published.
   *
   * \param use_local_topics Flag to publish topics in local namespace.
   * \param joints Names of the joints to publish.
   * \param interfaces Names of interfaces to publish.
   * \param map_interface_to_joint_state.{HW_IF_POSITION|HW_IF_VELOCITY|HW_IF_EFFORT} mapping
   * between custom interface names and standard names in sensor_msgs::msg::JointState message.
   *
   * Publishes to:
   * - \b joint_states (sensor_msgs::msg::JointState): Joint states related to movement
   * (position, velocity, effort).
   * - \b dynamic_joint_states (control_msgs::msg::DynamicJointState): Joint states regardless of
   * its interface type.
   */
  class GPSSensorBroadcaster : public controller_interface::ControllerInterface
  {
  public:
    GPS_SENSOR_BROADCASTER_PUBLIC
    GPSSensorBroadcaster();

    GPS_SENSOR_BROADCASTER_PUBLIC
    controller_interface::InterfaceConfiguration command_interface_configuration() const override;

    GPS_SENSOR_BROADCASTER_PUBLIC
    controller_interface::InterfaceConfiguration state_interface_configuration() const override;

    GPS_SENSOR_BROADCASTER_PUBLIC
    controller_interface::return_type update(
        const rclcpp::Time &time, const rclcpp::Duration &period) override;

    GPS_SENSOR_BROADCASTER_PUBLIC
    controller_interface::CallbackReturn on_init() override;

    GPS_SENSOR_BROADCASTER_PUBLIC
    controller_interface::CallbackReturn on_configure(
        const rclcpp_lifecycle::State &previous_state) override;

    GPS_SENSOR_BROADCASTER_PUBLIC
    controller_interface::CallbackReturn on_activate(
        const rclcpp_lifecycle::State &previous_state) override;

    GPS_SENSOR_BROADCASTER_PUBLIC
    controller_interface::CallbackReturn on_deactivate(
        const rclcpp_lifecycle::State &previous_state) override;

  protected:
    bool init_joint_data();
    void init_joint_state_msg();
    bool use_all_available_interfaces() const;

  protected:
    // Optional parameters
    std::shared_ptr<ParamListener> param_listener_;
    Params params_;

    //  For the NavSaFix message,
    //  we store the name of joints with compatible interfaces
    std::shared_ptr<rclcpp::Publisher<sensor_msgs::msg::NavSatFix>> gps_sensor_publisher_;
    std::shared_ptr<realtime_tools::RealtimePublisher<sensor_msgs::msg::NavSatFix>>
        realtime_gps_sensor_publisher_;

  };

} // namespace gps_sensor_broadcaster

#endif // GPS_SENSOR_BROADCASTER__GPS_SENSOR_BROADCASTER_HPP_
